/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Pool(props) {
  const { nodes, materials } = useGLTF("/pluspool ny.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.Material}
        scale={[88.238/30, 0.46/30, 38.428/30]}
        rotation = {[Math.PI / 0.01, Math.PI / 0.75, 0]}
      />
    </group>
  );
}

useGLTF.preload("/pluspool ny.glb");
